package com.itheima.health.constant;

/**
 * 消息常量
 */
public interface MessageConstant {
    String CHECKGROUP_SETMEAL_FAIL="检查组被套餐管理，删除失败";
    String SETMEAL_ORDER_FAIL = "套餐已经被预约，删除失败";
    String CHECKGROUP_ARRAY_ID = "查询检查项的id成功";
    String CHECKITEM_IN_USE = "此检查项已经被使用了，不能删除";
    String DELETE_CHECKITEM_FAIL = "删除检查项失败";
    String DELETE_CHECKITEM_SUCCESS = "删除检查项成功";
    String ADD_CHECKITEM_SUCCESS = "新增检查项成功";
    String ADD_CHECKITEM_FAIL = "新增检查项失败";
    String EDIT_CHECKITEM_FAIL = "编辑检查项失败";
    String EDIT_CHECKITEM_SUCCESS = "编辑检查项成功";
    String QUERY_CHECKITEM_SUCCESS = "查询检查项成功";
    String QUERY_CHECKITEM_FAIL = "查询检查项失败";
    String UPLOAD_SUCCESS = "上传成功";
    String ADD_CHECKGROUP_FAIL = "新增检查组失败";
    String ADD_CHECKGROUP_SUCCESS = "新增检查组成功";
    String DELETE_CHECKGROUP_FAIL = "删除检查组失败";
    String DELETE_CHECKGROUP_SUCCESS = "删除检查组成功";
    String QUERY_CHECKGROUP_SUCCESS = "查询检查组成功";
    String QUERY_CHECKGROUP_FAIL = "查询检查组失败";
    String EDIT_CHECKGROUP_FAIL = "编辑检查组失败";
    String EDIT_CHECKGROUP_SUCCESS = "编辑检查组成功";
    String PIC_UPLOAD_SUCCESS = "图片上传成功";
    String PIC_UPLOAD_FAIL = "图片上传失败";
    String ADD_SETMEAL_FAIL = "新增套餐失败";
    String ADD_SETMEAL_SUCCESS = "新增套餐成功";
    String UPDATE_SETMEAL_FAIL = "编辑套餐失败";
    String UPDATE_SETMEAL_SUCCESS = "编辑套餐成功";
    String DELETE_SETMEAL_SUCCESS = "删除套餐成功";
    String DELETE_SETMEAL_FAIL = "删除套餐失败";
    String IMPORT_ORDERSETTING_FAIL = "批量导入预约设置数据失败";
    String IMPORT_ORDERSETTING_SUCCESS = "批量导入预约设置数据成功";
    String GET_ORDERSETTING_SUCCESS = "获取预约设置数据成功";
    String GET_ORDERSETTING_FAIL = "获取预约设置数据失败";
    String ORDERSETTING_SUCCESS = "预约设置成功";
    String ORDERSETTING_FAIL = "预约设置失败";
    String ADD_MEMBER_FAIL = "新增会员失败";
    String ADD_MEMBER_SUCCESS = "新增会员成功";
    String DELETE_MEMBER_FAIL = "删除会员失败";
    String DELETE_MEMBER_SUCCESS = "删除会员成功";
    String EDIT_MEMBER_FAIL = "编辑会员失败";
    String EDIT_MEMBER_SUCCESS = "编辑会员成功";
    String TELEPHONE_VALIDATECODE_NOTNULL = "手机号和验证码都不能为空";
    String LOGIN_SUCCESS = "登录成功";
    String VALIDATECODE_ERROR = "验证码输入错误";
    String QUERY_ORDER_SUCCESS = "查询预约信息成功";
    String QUERY_ORDER_FAIL = "查询预约信息失败";
    String QUERY_SETMEALLIST_SUCCESS = "查询套餐列表数据成功";
    String QUERY_SETMEALLIST_FAIL = "查询套餐列表数据失败";
    String QUERY_SETMEAL_SUCCESS = "查询套餐数据成功";
    String QUERY_SETMEAL_FAIL = "查询套餐数据失败";
    String SEND_VALIDATECODE_FAIL = "验证码发送失败";
    String SEND_VALIDATECODE_SUCCESS = "验证码发送成功";
    String SELECTED_DATE_CANNOT_ORDER = "所选日期不能进行体检预约";
    String ORDER_FULL = "预约已满";
    String HAS_ORDERED = "已经完成预约，不能重复预约";
    String ORDER_SUCCESS = "预约成功";
    String GET_USERNAME_SUCCESS = "获取当前登录用户名称成功";
    String GET_USERNAME_FAIL = "获取当前登录用户名称失败";
    String GET_MENU_SUCCESS = "获取当前登录用户菜单成功";
    String GET_MENU_FAIL = "获取当前登录用户菜单失败";
    String GET_MEMBER_NUMBER_REPORT_SUCCESS = "获取会员统计数据成功";
    String GET_MEMBER_NUMBER_REPORT_FAIL = "获取会员统计数据失败";
    String GET_SETMEAL_COUNT_REPORT_SUCCESS = "获取套餐统计数据成功";
    String GET_SETMEAL_COUNT_REPORT_FAIL = "获取套餐统计数据失败";
    String GET_BUSINESS_REPORT_SUCCESS = "获取运营统计数据成功";
    String GET_BUSINESS_REPORT_FAIL = "获取运营统计数据失败";
    String GET_SETMEAL_LIST_SUCCESS = "查询套餐列表数据成功";
    String GET_SETMEAL_LIST_FAIL = "查询套餐列表数据失败";
}